In [2]:
import tensorflow as tf
import pandas as pd

dataset_directory = '../archive/labels_train.csv'
df = pd.read_csv(dataset_directory)

print(df)



                          frame  xmin  xmax  ymin  ymax  class_id
0       1478019952686311006.jpg   237   251   143   155         1
1       1478019952686311006.jpg   437   454   120   186         3
2       1478019953180167674.jpg   218   231   146   158         1
3       1478019953689774621.jpg   171   182   141   154         2
4       1478019953689774621.jpg   179   191   144   155         1
...                         ...   ...   ...   ...   ...       ...
132401  1479506176491553178.jpg   166   186   139   156         1
132402  1479506176491553178.jpg   182   204   142   153         1
132403  1479506176491553178.jpg   239   261   139   155         1
132404  1479506176491553178.jpg   259   280   139   157         1
132405  1479506176491553178.jpg   284   324   137   168         1

[132406 rows x 6 columns]


In [3]:
features = df.drop(columns=['class_id'])
label = df['class_id']

#print(features)
print(label)

0         1
1         3
2         1
3         2
4         1
         ..
132401    1
132402    1
132403    1
132404    1
132405    1
Name: class_id, Length: 132406, dtype: int64


In [6]:
#loading the dataset csv with tf


tf_dataset = tf.data.Dataset.from_tensor_slices((dict(features),label))


In [9]:
for feature, label in tf_dataset.take(1):
    print('features', feature)
    print('label', label)

features {'frame': <tf.Tensor: shape=(), dtype=string, numpy=b'1478019952686311006.jpg'>, 'xmin': <tf.Tensor: shape=(), dtype=int64, numpy=237>, 'xmax': <tf.Tensor: shape=(), dtype=int64, numpy=251>, 'ymin': <tf.Tensor: shape=(), dtype=int64, numpy=143>, 'ymax': <tf.Tensor: shape=(), dtype=int64, numpy=155>}
label tf.Tensor(1, shape=(), dtype=int64)
